# vi: set ft=dockerfile :

FROM centos:7
MAINTAINER Kazuhisa Hara <khara@sios.com>

RUN yum install -y --setopt=tsflags=nodocs \
        epel-release \
        bash bash-completion \
        screen \
        vim && \
    yum install -y --setopt=tsflags=nodocs \
        golang \
        jq \
        vim-go && \
    rm -rf /var/cache/yum

WORKDIR /root

RUN echo "shell /usr/bin/bash" > /root/.screenrc
RUN go get -u gopkg.in/oauth2.v3 github.com/dgrijalva/jwt-go github.com/tidwall/buntdb

ADD user.json /root/user.json
ADD server.go /root/server.go
RUN go build server.go

EXPOSE 9096
CMD /bin/bash
